### PR TITLE
feat: use cookie consent to specify using matomo cookies

### PR DESCRIPTION
**Pull request by tinect**
I've added the cookie consent minimally invasive :-)

`cookie.MatomoDescription` should give the ability to specify a short user-friendly test, f.e.: we are self-hosted, no data selling, ......

Additionally, I've added an action to create releases. Could you please register this repository to packagist.org and then creating a tag?
Tagging will automatically build and publish a release on github.

### CODE REVIEW

**Comment by DerKnerd** [comment]
Thank you for supporting this plugin further :slightly_smiling_face: I created a packagist package, check here: https://packagist.org/packages/jinya/matomo-shopware-plugin

**Comment by tinect** [comment]
Hey @DerKnerd,
it looks like you created a release instead of just a tag? [The build failed](https://github.com/Jinya-CMS/matomo-shopware-plugin/actions/runs/984307790) :-(

The result is, that there is no compiles JS in current 0.0.1 release (src/Resources/app/storefront/dist/).
Don't know if it's possible to add a compiled zip, to be re-registered at packages. You could try by adding this file:
[JinyaMatomo.zip](https://github.com/Jinya-CMS/matomo-shopware-plugin/files/6738512/JinyaMatomo.zip)

 If not, a new additional release has to be created by just creating a tag.

**Comment by DerKnerd** [comment]
Hey @tinect,

I deleted the release and the tag and pushed the tag again, should work now :slightly_smiling_face:

**Comment by tinect** [comment]
Sadly, packagist don't update existing releases. So installing with composer it still doesn't contain the compiled JS :-(

**Comment by DerKnerd** [comment]
@tinect I created a new dummy release, hope it works now :)

**Pull request merged**
