### PR TITLE
Add new configs

### PR DESCRIPTION
**Pull request by tinect**
+ removed duplicated trackPageView

### CODE REVIEW

**Comment by DerKnerd** [comment]
Hey,

thanks for the contribution. Can you add the cookie notice to the plugin if it uses cookies?

Greetings
Knerd

**Comment by tinect** [comment]
> Hey,
> 
> thanks for the contribution. Can you add the cookie notice to the plugin if it uses cookies?
> 
> Greetings
> Knerd

Hey @DerKnerd, 
but then there should be one more config to specify the cookie consent to make configurable or not? 🤔 
If it's self-hosted, there should be no need, should it?

**Comment by DerKnerd** [comment]
Hey @tinect,

good question. The cookies are not necessary and track uses, so to my understanding you do need to display a cookie notice.

**Comment by tinect** [comment]
Oh, damn. missread. For now, I would remove the new config and come back again with topic. Okay?

**Comment by DerKnerd** [comment]
Hey @tinect,

yeah looks good to me like that :slightly_smiling_face: Thanks for the contribution :slightly_smiling_face:

**Pull request merged**
